//! `sc up` / `down` / `restart` / `log` — user-level daemon lifecycle.
//!
//! Two backends, one mental model ("bring the daemon up in the background,
//! auto-restart on crash, state under `$HOME`, no sudo"):
//!   - **Linux:** a per-user systemd unit at
//!     `~/.config/systemd/user/safeclaw.service`, driven by `systemctl --user`.
//!   - **macOS:** a LaunchAgent at
//!     `~/Library/LaunchAgents/pro.safeclaw.daemon.plist`, driven by
//!     `launchctl` (RunAtLoad + KeepAlive = the systemd unit's start +
//!     `Restart=on-failure`). Logs go to `~/.safeclaw/daemon.log`.
//! Other platforms fall back to `sc serve` (foreground).
//!
//! Why user-level (not system-level)?
//! - No sudo required — the daemon runs as the same user that called `sc start`.
//! - Vault state lives under `$HOME/.safeclaw/`, owned by the same user.
//! - Encapsulates "this user's SafeClaw daemon" cleanly. Multi-user hosts
//!   work too, each user gets their own daemon.
//!
//! Operators running SafeClaw as a system service (root-owned, the dev VM
//! shape) should write their own `/etc/systemd/system/safeclaw.service`
//! and not touch these commands.

use crate::config::LogArgs;
use std::process::Command as ProcCommand;

const UNIT_BASENAME: &str = "safeclaw.service";
/// First line of every unit we generate. The idempotency guard refuses to
/// overwrite a unit that lacks this marker (a hand-written one) unless
/// `--force` is passed.
const UNIT_MARKER: &str = "# Generated by safeclaw — do not edit; re-run `sc up` to refresh.";
/// Stable substring used for *detection* (the "is this our unit?" guard).
/// The full `UNIT_MARKER`'s trailing hint has drifted across versions
/// (`sc custodian start` → `sc up`), so detecting on the whole string
/// orphaned units written by older builds — `sc` stopped recognizing its
/// own unit and refused to manage it. Detect on this invariant prefix; all
/// safeclaw-generated units (past and present) start the marker line with it.
const UNIT_MARKER_DETECT: &str = "# Generated by safeclaw";

// ── macOS: launchd LaunchAgent (the per-user, no-sudo analog of the Linux
//    user-systemd unit above — RunAtLoad + KeepAlive gives the same
//    "background, auto-restart on crash, state under $HOME" semantics). ──
#[cfg(target_os = "macos")]
const LAUNCHD_LABEL: &str = "pro.safeclaw.daemon";
/// XML-comment marker mirroring `UNIT_MARKER` — the same idempotency guard
/// (never clobber a hand-written plist at our path unless `--force`).
#[cfg(target_os = "macos")]
const PLIST_MARKER_DETECT: &str = "Generated by safeclaw";

#[cfg(target_os = "macos")]
fn launchd_plist_path() -> Result<std::path::PathBuf, String> {
    let home = dirs::home_dir().ok_or("no home dir")?;
    Ok(home
        .join("Library/LaunchAgents")
        .join(format!("{LAUNCHD_LABEL}.plist")))
}

#[cfg(target_os = "macos")]
fn launchd_log_path() -> Result<std::path::PathBuf, String> {
    let home = dirs::home_dir().ok_or("no home dir")?;
    Ok(home.join(".safeclaw").join("daemon.log"))
}

/// Escape a string for inclusion in plist XML text (paths / env values).
#[cfg(target_os = "macos")]
fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

#[cfg(target_os = "macos")]
fn run_launchctl(args: &[&str], action: &str) -> Result<(), String> {
    let output = ProcCommand::new("launchctl")
        .args(args)
        .output()
        .map_err(|e| format!("spawn launchctl: {}", e))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("launchctl {} failed: {}", action, stderr.trim()));
    }
    Ok(())
}

/// The REAL liveness signal on macOS: something answers on the daemon's control
/// port. A launchd job can be *loaded* yet its process *dead* — a clean exit
/// under `KeepAlive{SuccessfulExit=false}` (which an `sc upgrade` bounce can
/// leave behind) is not restarted, so `launchctl list` still lists the job while
/// nothing listens. Reading "loaded" as "running" made `sc up` report success
/// over a dead daemon; a cheap TCP connect is the honest check.
#[cfg(target_os = "macos")]
fn control_port_alive() -> bool {
    let addr = std::net::SocketAddr::from((std::net::Ipv4Addr::LOCALHOST, crate::config::CONTROL_PORT));
    std::net::TcpStream::connect_timeout(&addr, std::time::Duration::from_millis(400)).is_ok()
}

/// Poll the control port until it answers or we give up (~20s). The daemon binds
/// only AFTER `pull_on_start`, which now auto-discovers the account's vaults and
/// pulls each one's sealed blob before serving — on a multi-vault account that
/// cold start runs well past the old 6s window, so a bounce would false-alarm
/// "nothing answering" even though the daemon comes up a beat later. Poll long
/// enough to cover it; a genuinely dead daemon still errors, just later.
#[cfg(target_os = "macos")]
fn wait_for_control_port() -> bool {
    for _ in 0..80 {
        if control_port_alive() {
            return true;
        }
        std::thread::sleep(std::time::Duration::from_millis(250));
    }
    false
}

/// This login session's uid — needed to name the launchd GUI domain explicitly
/// (`gui/<uid>`). Declaring `getuid` directly avoids taking on the `libc` crate
/// for one call; `uid_t` is `u32` on Darwin.
#[cfg(target_os = "macos")]
fn current_uid() -> u32 {
    extern "C" {
        fn getuid() -> u32;
    }
    unsafe { getuid() }
}

/// The GUI domain (`gui/<uid>`) our LaunchAgent lives in, and the fully-qualified
/// service target within it. Pinning the domain explicitly is what stops the
/// legacy verbs' "wrong session / not found in domain" wedge.
#[cfg(target_os = "macos")]
fn gui_domain() -> String {
    format!("gui/{}", current_uid())
}
#[cfg(target_os = "macos")]
fn gui_service() -> String {
    format!("gui/{}/{}", current_uid(), LAUNCHD_LABEL)
}

/// Bring the LaunchAgent to "one fresh process, running" from ANY prior state,
/// using ONLY the modern domain-pinned verbs. This is the launchd analog of
/// systemd's "daemon-reload + restart", built to converge whether the job is
/// absent, loaded-but-dead, disabled (a legacy `unload -w` override), or
/// domain-wedged.
///
/// Every launchctl step is BEST-EFFORT — "already bootstrapped" / "not found"
/// are expected along the way and must not abort the sequence. The SOLE success
/// criterion is the control port answering (the honest `is-active`), never a
/// launchctl exit code. `bootout` clears the old registration, `enable` clears a
/// lingering disable override, `bootstrap` re-registers (RunAtLoad starts it),
/// and `kickstart -k` forces a fresh process (covering a RunAtLoad that didn't
/// fire or a job we couldn't boot out).
#[cfg(target_os = "macos")]
fn launchd_converge(plist_arg: &str) -> Result<(), String> {
    let domain = gui_domain();
    let service = gui_service();
    let _ = run_launchctl(&["bootout", &service], "bootout");
    let _ = run_launchctl(&["enable", &service], "enable");
    let _ = run_launchctl(&["bootstrap", &domain, plist_arg], "bootstrap");
    let _ = run_launchctl(&["kickstart", "-k", &service], "kickstart");
    if wait_for_control_port() {
        Ok(())
    } else {
        Err(
            "the LaunchAgent was (re)started but nothing is answering on the control port, \
             check `sc log`"
                .to_string(),
        )
    }
}

#[cfg(target_os = "linux")]
pub async fn run_start_systemd(force: bool) -> Result<(), String> {
    let bin =
        std::env::current_exe().map_err(|e| format!("can't find current binary path: {}", e))?;
    let bin_str = bin.to_string_lossy().to_string();

    // Collect any SAFECLAW_* env vars set in the calling shell — these
    // become Environment= lines in the unit. The user controls config
    // by setting env vars *before* `sc start`; flags are ignored here
    // (they'd be invisible after install, which is worse).
    let mut env_lines = Vec::new();
    for (k, v) in std::env::vars() {
        // Don't leak the agent-facing SAFECLAW_API_KEY into the daemon's
        // env — the daemon reads its api-key from the FILE `~/.safeclaw/api-key`
        // (provisioned below), and a stray/foreign value in the operator's
        // shell must not be adopted as the broker key.
        if k.starts_with("SAFECLAW_") && k != "SAFECLAW_API_KEY" {
            // systemd unit syntax: quote the value to allow spaces/=.
            // Escape any " inside.
            let v_escaped = v.replace('"', "\\\"");
            env_lines.push(format!("Environment=\"{}={}\"", k, v_escaped));
        }
    }
    // Broker auth is the cloud-synced agent-key hash-set (agent ≡ api-key),
    // refreshed at runtime by `crate::sync` — there's no machine-local key file
    // to provision here. See [[project_vault_agent_architecture_2026_06_25]].
    let env_block = if env_lines.is_empty() {
        String::new()
    } else {
        format!("{}\n", env_lines.join("\n"))
    };

    let unit = format!(
        "{UNIT_MARKER}\n\
         [Unit]\n\
         Description=SafeClaw daemon (user)\n\
         After=network.target\n\
         \n\
         [Service]\n\
         Type=simple\n\
         {env_block}\
         ExecStart={bin} serve\n\
         Restart=on-failure\n\
         RestartSec=5\n\
         \n\
         [Install]\n\
         WantedBy=default.target\n",
        env_block = env_block,
        bin = bin_str,
    );

    let unit_dir = dirs::config_dir()
        .ok_or("can't locate user config dir (XDG_CONFIG_HOME)")?
        .join("systemd/user");
    std::fs::create_dir_all(&unit_dir)
        .map_err(|e| format!("create {}: {}", unit_dir.display(), e))?;
    let unit_path = unit_dir.join(UNIT_BASENAME);
    // Idempotency guard: never silently clobber a unit we didn't generate.
    // A unit lacking the (version-stable) safeclaw marker prefix is
    // hand-written; refuse unless --force. We match `UNIT_MARKER_DETECT`
    // (not the full `UNIT_MARKER`) so units written by older builds — whose
    // marker tail differs — are still recognized as ours.
    if !force {
        if let Ok(existing) = std::fs::read_to_string(&unit_path) {
            if !existing.contains(UNIT_MARKER_DETECT) {
                return Err(format!(
                    "{} already exists and was not generated by safeclaw \
                     (no marker). Refusing to overwrite. Re-run with `--force` \
                     to replace it, or `sc up` to just start the existing unit.",
                    unit_path.display()
                ));
            }
        }
    }
    std::fs::write(&unit_path, &unit)
        .map_err(|e| format!("write {}: {}", unit_path.display(), e))?;
    // Unit may embed SAFECLAW_ADMIN_KEY and other secrets via
    // Environment= lines. Tighten to user-only so other accounts on a
    // multi-user host can't read them.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&unit_path, std::fs::Permissions::from_mode(0o600))
            .map_err(|e| format!("chmod 0600 {}: {}", unit_path.display(), e))?;
    }

    run_systemctl(&["daemon-reload"], "daemon-reload")?;
    run_systemctl(&["enable", "--now", UNIT_BASENAME], "enable+start")?;

    eprintln!("✓ daemon enabled and running ({})", unit_path.display());
    eprintln!("  binary:   {}", bin_str);
    if !env_lines.is_empty() {
        eprintln!("  env:      {} SAFECLAW_* var(s) embedded", env_lines.len());
    }
    eprintln!("  broker:   requires an agent key (synced from your account); mint one with `sc agent add` or the dashboard's \"Connect a new agent\"");
    eprintln!();
    eprintln!("  next: `sc login --pair-token <token>` to connect this daemon to your vault (token from the dashboard)");
    eprintln!("        `sc log -f` to tail, `sc down` to stop, `sc restart` to reload");
    Ok(())
}

#[cfg(target_os = "macos")]
pub async fn run_start_systemd(force: bool) -> Result<(), String> {
    let bin =
        std::env::current_exe().map_err(|e| format!("can't find current binary path: {}", e))?;
    let bin_str = bin.to_string_lossy().to_string();

    // Same policy as the systemd path: the daemon inherits SAFECLAW_* set in
    // the calling shell (so `SAFECLAW_PORT=<p> sc up` moves the port and it
    // sticks across restarts), EXCEPT the agent-facing SAFECLAW_API_KEY.
    let mut env_entries = Vec::new();
    for (k, v) in std::env::vars() {
        if k.starts_with("SAFECLAW_") && k != "SAFECLAW_API_KEY" {
            env_entries.push(format!(
                "    <key>{}</key><string>{}</string>",
                xml_escape(&k),
                xml_escape(&v)
            ));
        }
    }
    let env_block = if env_entries.is_empty() {
        String::new()
    } else {
        format!(
            "  <key>EnvironmentVariables</key>\n  <dict>\n{}\n  </dict>\n",
            env_entries.join("\n")
        )
    };

    let log_path = launchd_log_path()?;
    let log_str = log_path.to_string_lossy().to_string();
    // KeepAlive{SuccessfulExit=false} = restart on crash, not on clean exit —
    // the launchd analog of the unit's `Restart=on-failure`.
    let plist = format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <!-- {marker} -->\n\
         <!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n\
         <plist version=\"1.0\">\n\
         <dict>\n\
         \x20 <key>Label</key>\n\
         \x20 <string>{label}</string>\n\
         \x20 <key>ProgramArguments</key>\n\
         \x20 <array>\n\
         \x20   <string>{bin}</string>\n\
         \x20   <string>serve</string>\n\
         \x20 </array>\n\
         {env_block}\
         \x20 <key>RunAtLoad</key>\n\
         \x20 <true/>\n\
         \x20 <key>KeepAlive</key>\n\
         \x20 <dict><key>SuccessfulExit</key><false/></dict>\n\
         \x20 <key>ProcessType</key>\n\
         \x20 <string>Background</string>\n\
         \x20 <key>StandardOutPath</key>\n\
         \x20 <string>{log}</string>\n\
         \x20 <key>StandardErrorPath</key>\n\
         \x20 <string>{log}</string>\n\
         </dict>\n\
         </plist>\n",
        marker = UNIT_MARKER.trim_start_matches("# "),
        label = LAUNCHD_LABEL,
        bin = xml_escape(&bin_str),
        env_block = env_block,
        log = xml_escape(&log_str),
    );

    let plist_path = launchd_plist_path()?;
    let dir = plist_path.parent().ok_or("bad LaunchAgents path")?;
    std::fs::create_dir_all(dir).map_err(|e| format!("create {}: {}", dir.display(), e))?;
    // Ensure the log's parent (~/.safeclaw) exists so launchd can open it.
    if let Some(logdir) = log_path.parent() {
        std::fs::create_dir_all(logdir)
            .map_err(|e| format!("create {}: {}", logdir.display(), e))?;
    }
    // Idempotency guard (mirrors the systemd path): refuse to overwrite a
    // plist we didn't generate unless --force.
    if !force {
        if let Ok(existing) = std::fs::read_to_string(&plist_path) {
            if !existing.contains(PLIST_MARKER_DETECT) {
                return Err(format!(
                    "{} already exists and was not generated by safeclaw. \
                     Refusing to overwrite. Re-run with `--force` to replace it.",
                    plist_path.display()
                ));
            }
        }
    }
    std::fs::write(&plist_path, &plist)
        .map_err(|e| format!("write {}: {}", plist_path.display(), e))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&plist_path, std::fs::Permissions::from_mode(0o600))
            .map_err(|e| format!("chmod 0600 {}: {}", plist_path.display(), e))?;
    }

    let plist_arg = plist_path.to_string_lossy().to_string();
    // Register + start via the modern domain-pinned verbs, converging from any
    // prior state; success is verified by the control port, not launchctl.
    launchd_converge(&plist_arg)?;

    eprintln!("✓ daemon installed and running ({})", plist_path.display());
    eprintln!("  binary:   {}", bin_str);
    if !env_entries.is_empty() {
        eprintln!(
            "  env:      {} SAFECLAW_* var(s) embedded",
            env_entries.len()
        );
    }
    eprintln!("  logs:     {}", log_str);
    eprintln!();
    eprintln!("  next: `sc login --pair-token <token>` to connect this daemon to your vault (token from the dashboard)");
    eprintln!("        `sc log -f` to tail, `sc down` to stop, `sc restart` to reload");
    Ok(())
}

#[cfg(not(any(target_os = "linux", target_os = "macos")))]
pub async fn run_start_systemd(_force: bool) -> Result<(), String> {
    Err("`sc up` (service mode) is Linux/macOS-only. Use `sc serve` to run in this process.".into())
}

/// Idempotent "ensure the daemon is running" — the skill's lazy-start target.
/// Starts the user-level unit only if it isn't already active; never rewrites
/// the unit (so it can't clobber config or race a concurrent start). If no
/// unit is installed yet, it tells the user to run `sc up` once.
#[cfg(target_os = "linux")]
pub fn run_ensure_running() -> Result<(), String> {
    // Already active? Nothing to do — this is the common case the skill hits
    // every session, so keep it cheap and silent-ish.
    let active = ProcCommand::new("systemctl")
        .args(["--user", "is-active", "--quiet", UNIT_BASENAME])
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    if active {
        eprintln!("✓ daemon already running");
        return Ok(());
    }
    // Not active. If the unit exists, just start it (no rewrite). Otherwise
    // the daemon was never installed as a service — guide the user.
    ensure_unit_installed().map_err(|_| {
        "daemon is not running and no service is installed — run `sc up` once to install it"
            .to_string()
    })?;
    run_systemctl(&["start", UNIT_BASENAME], "start")?;
    eprintln!("✓ daemon started");
    Ok(())
}

#[cfg(target_os = "macos")]
pub fn run_ensure_running() -> Result<(), String> {
    let plist_path = launchd_plist_path()?;
    if !plist_path.exists() {
        return Err(
            "daemon is not running and no LaunchAgent is installed — run `sc up` once to install it"
                .to_string(),
        );
    }
    // Liveness = the control port answers, NOT `launchctl list` (a job can be
    // loaded-but-dead; see control_port_alive). Already up → cheap no-op: never
    // tear down a healthy daemon on a routine `sc up` (that would drop the
    // in-memory vault keys and re-lock). Only converge when nothing answers.
    if control_port_alive() {
        eprintln!("✓ daemon already running");
        return Ok(());
    }
    let plist_arg = plist_path.to_string_lossy().to_string();
    launchd_converge(&plist_arg)?;
    eprintln!("✓ daemon started");
    Ok(())
}

#[cfg(not(any(target_os = "linux", target_os = "macos")))]
pub fn run_ensure_running() -> Result<(), String> {
    Err("`sc up` (service mode) is Linux/macOS-only. Use `sc serve` to run in this process.".into())
}

#[cfg(target_os = "linux")]
pub fn run_stop() -> Result<(), String> {
    ensure_unit_installed()?;
    run_systemctl(&["stop", UNIT_BASENAME], "stop")?;
    eprintln!("✓ daemon stopped");
    Ok(())
}

#[cfg(target_os = "macos")]
pub fn run_stop() -> Result<(), String> {
    let plist_path = launchd_plist_path()?;
    if !plist_path.exists() {
        return Err("no LaunchAgent installed — run `sc up` first".to_string());
    }
    // Modern equivalent of `unload -w`: bootout removes it from the domain (stops
    // the process); disable persists "stay down" across logins until the next
    // `sc up` re-enables it. Both best-effort — an already-stopped daemon is a
    // success, not an error.
    let service = gui_service();
    let _ = run_launchctl(&["bootout", &service], "bootout");
    let _ = run_launchctl(&["disable", &service], "disable");
    eprintln!("✓ daemon stopped");
    Ok(())
}

#[cfg(not(any(target_os = "linux", target_os = "macos")))]
pub fn run_stop() -> Result<(), String> {
    Err("`sc down` (service mode) is Linux/macOS-only.".into())
}

#[cfg(target_os = "linux")]
pub fn run_restart() -> Result<(), String> {
    ensure_unit_installed()?;
    run_systemctl(&["restart", UNIT_BASENAME], "restart")?;
    eprintln!("✓ daemon restarted");
    Ok(())
}

#[cfg(target_os = "macos")]
pub fn run_restart() -> Result<(), String> {
    let plist_path = launchd_plist_path()?;
    if !plist_path.exists() {
        return Err("no LaunchAgent installed — run `sc up` first".to_string());
    }
    let plist_arg = plist_path.to_string_lossy().to_string();
    // Always converge to a FRESH process (the point of restart / the `sc upgrade`
    // bounce). The modern verbs + control-port verify can't silently no-op the
    // way the old `unload`/`load -w` pair did when a just-exited job wasn't
    // relaunched. The caller re-unlocks afterward.
    launchd_converge(&plist_arg)?;
    eprintln!("✓ daemon restarted");
    Ok(())
}

#[cfg(not(any(target_os = "linux", target_os = "macos")))]
pub fn run_restart() -> Result<(), String> {
    Err("`sc restart` (service mode) is Linux/macOS-only.".into())
}

#[cfg(target_os = "linux")]
pub fn run_log(args: LogArgs) -> Result<(), String> {
    ensure_unit_installed()?;
    let n = args.tail.to_string();
    let mut cmd = ProcCommand::new("journalctl");
    cmd.args(["--user", "-u", UNIT_BASENAME, "-n", &n]);
    // `-o cat` prints only the daemon's own log line — which already carries an
    // ISO timestamp + level + module — dropping journald's redundant
    // `<date> <host> sc[pid]:` prefix that otherwise doubles the timestamp and
    // pushes the useful message off the right edge. `--raw` restores the full
    // journald format (local wall-clock, host, pid) when you want it.
    if !args.raw {
        cmd.args(["-o", "cat"]);
    }
    if args.follow {
        cmd.arg("-f");
    }
    // Inherit stdio so journalctl prints directly + Ctrl-C works.
    let status = cmd
        .status()
        .map_err(|e| format!("spawn journalctl: {}", e))?;
    if !status.success() {
        return Err(format!("journalctl exited with status {}", status));
    }
    Ok(())
}

#[cfg(target_os = "macos")]
pub fn run_log(args: LogArgs) -> Result<(), String> {
    // launchd has no journal; the daemon's stdout/stderr land in the plist's
    // StandardOutPath. Tail that file (the daemon already prefixes each line
    // with an ISO timestamp + level + module, so there's no journald-style
    // wrapper to strip — `--raw` is accepted for parity but a no-op here).
    let log_path = launchd_log_path()?;
    if !log_path.exists() {
        return Err(format!(
            "no daemon log at {} yet — run `sc up` first",
            log_path.display()
        ));
    }
    let n = args.tail.to_string();
    let mut cmd = ProcCommand::new("tail");
    cmd.args(["-n", &n]);
    if args.follow {
        cmd.arg("-f");
    }
    cmd.arg(&log_path);
    let status = cmd.status().map_err(|e| format!("spawn tail: {}", e))?;
    if !status.success() {
        return Err(format!("tail exited with status {}", status));
    }
    Ok(())
}

#[cfg(not(any(target_os = "linux", target_os = "macos")))]
pub fn run_log(_args: LogArgs) -> Result<(), String> {
    Err("`sc log` (service mode) is Linux/macOS-only.".into())
}

#[cfg(target_os = "linux")]
fn ensure_unit_installed() -> Result<(), String> {
    let unit_path = dirs::config_dir()
        .ok_or("can't locate user config dir")?
        .join("systemd/user")
        .join(UNIT_BASENAME);
    if !unit_path.exists() {
        return Err(format!(
            "no systemd unit at {} — run `sc up` first to install it",
            unit_path.display()
        ));
    }
    Ok(())
}

/// True if the user-level systemd unit is already installed. Lets `sc up`
/// decide between first-time install (`run_start_systemd`) and the light
/// everyday ensure-running. False on non-Linux (no systemd unit concept).
pub fn unit_installed() -> bool {
    #[cfg(target_os = "linux")]
    {
        dirs::config_dir()
            .map(|d| d.join("systemd/user").join(UNIT_BASENAME).exists())
            .unwrap_or(false)
    }
    #[cfg(target_os = "macos")]
    {
        launchd_plist_path().map(|p| p.exists()).unwrap_or(false)
    }
    #[cfg(not(any(target_os = "linux", target_os = "macos")))]
    {
        false
    }
}

/// Migrate a stale unit whose ExecStart still calls the removed `custodian run`
/// subcommand to the new `serve` entrypoint, in place (preserving the embedded
/// env block), then daemon-reload. Returns Ok(true) if it rewrote anything;
/// no-op when the unit is missing or already current. Called by `sc up` and
/// `sc upgrade` BEFORE they (re)start the daemon, so removing `custodian`
/// doesn't break a unit installed by an older build.
#[cfg(target_os = "linux")]
pub fn reconcile_unit_execstart() -> Result<bool, String> {
    let unit_path = dirs::config_dir()
        .ok_or("can't locate user config dir")?
        .join("systemd/user")
        .join(UNIT_BASENAME);
    let Ok(contents) = std::fs::read_to_string(&unit_path) else {
        return Ok(false);
    };
    if !contents.contains(" custodian run") {
        return Ok(false);
    }
    let fixed = contents.replace(" custodian run", " serve");
    std::fs::write(&unit_path, &fixed)
        .map_err(|e| format!("rewrite unit {}: {}", unit_path.display(), e))?;
    let _ = run_systemctl(&["daemon-reload"], "daemon-reload");
    Ok(true)
}

#[cfg(not(target_os = "linux"))]
pub fn reconcile_unit_execstart() -> Result<bool, String> {
    Ok(false)
}

#[cfg(target_os = "linux")]
fn run_systemctl(args: &[&str], action: &str) -> Result<(), String> {
    let mut cmd = ProcCommand::new("systemctl");
    cmd.arg("--user");
    cmd.args(args);
    let output = cmd
        .output()
        .map_err(|e| format!("spawn systemctl: {}", e))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!(
            "systemctl --user {} failed: {}",
            action,
            stderr.trim()
        ));
    }
    Ok(())
}
